# ==============================================================================
# Generated by qmake (2.01a) (Qt 4.5.0-garden) on: ѕт 10. апр 22:23:55 2009
# This file is generated by qmake and should not be modified by the
# user.
#  Name        : Makefile_0xE92D4440.mk
#  Part of     : firuqt
#  Description : This file is used to call necessary targets on wrapper makefile
#                during normal Symbian build process.
#  Version     : 
#
# ==============================================================================



MAKE = make

do_nothing :
	@rem do_nothing

MAKMAKE: create_temps pre_targetdeps

LIB: create_temps pre_targetdeps

BLD: create_temps pre_targetdeps

ifeq "$(PLATFORM)" "WINSCW"
CLEAN: extension_clean winscw_deployment_clean
else
CLEAN: extension_clean
endif

CLEANLIB: do_nothing

RESOURCE: do_nothing

FREEZE: do_nothing

SAVESPACE: do_nothing

RELEASABLES: do_nothing

ifeq "$(PLATFORM)" "WINSCW"
FINAL: finalize winscw_deployment
else
FINAL: finalize
endif

pre_targetdeps : c:\S60\devices\SDK_32\firu\firuqt\Makefile
	-$(MAKE) -f "c:\S60\devices\SDK_32\firu\firuqt\Makefile" pre_targetdeps

create_temps : c:\S60\devices\SDK_32\firu\firuqt\Makefile
	-$(MAKE) -f "c:\S60\devices\SDK_32\firu\firuqt\Makefile" create_temps

extension_clean : c:\S60\devices\SDK_32\firu\firuqt\Makefile
	-$(MAKE) -f "c:\S60\devices\SDK_32\firu\firuqt\Makefile" extension_clean

finalize : c:\S60\devices\SDK_32\firu\firuqt\Makefile
	-$(MAKE) -f "c:\S60\devices\SDK_32\firu\firuqt\Makefile" finalize

winscw_deployment_clean : c:\S60\devices\SDK_32\firu\firuqt\Makefile
	-$(MAKE) -f "c:\S60\devices\SDK_32\firu\firuqt\Makefile" winscw_deployment_clean

winscw_deployment : c:\S60\devices\SDK_32\firu\firuqt\Makefile
	-$(MAKE) -f "c:\S60\devices\SDK_32\firu\firuqt\Makefile" winscw_deployment


